openapi: 3.0.0
info:
  title: API de Autenticación
  description: API con autenticación y autorización usando JWT sin firmar.
  version: 1.0.0
servers:
  - url: http://localhost:8081
paths:
  /auth/login:
    post:
      summary: Autenticación de usuario
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Token de autenticación
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
  /protected/userA:
    get:
      summary: Endpoint exclusivo para User A
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Mensaje para User A
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /protected/userB:
    get:
      summary: Endpoint exclusivo para User B
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Mensaje para User B
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /protected/shared:
    get:
      summary: Endpoint compartido
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Mensaje para ambos usuarios
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
